#!/bin/sh

sudo debconf-set-selections openssh-server.debconf
sudo apt install openssh-server
mkdir $HOME/.ssh
chmod 0700 $HOME/.ssh
touch $HOME/.ssh/authorized_keys
cat new-server.pub >> $HOME/.ssh/authorized_keys
ip addr